controllers:
    resource: ../src/Controller/
    type: attribute

app_directory:
    resource: 'routes/application'
    name_prefix: api_
    prefix: /api/
    type: directory

api_login_check:
    path: /api/login_check
